#!/bin/bash

# cilengitide
python prepare_input.py \
    chai \
    "CC(C)[C@H]1C(=O)N[C@@H](CCCNC(N)=[NH2+])C(=O)NCC(=O)N[C@@H](CC(=O)[O-])C(=O)N[C@H](Cc2ccccc2)C(=O)N1C" \
    data/cilengitide/cilengitide_chai_input.fasta

python prepare_input.py \
    boltz \
    "CC(C)[C@H]1C(=O)N[C@@H](CCCNC(N)=[NH2+])C(=O)NCC(=O)N[C@@H](CC(=O)[O-])C(=O)N[C@H](Cc2ccccc2)C(=O)N1C" \
    data/cilengitide/cilengitide_boltz_input.fasta

python prepare_input.py \
    af3 \
    "CC(C)[C@H]1C(=O)N[C@@H](CCCNC(N)=[NH2+])C(=O)NCC(=O)N[C@@H](CC(=O)[O-])C(=O)N[C@H](Cc2ccccc2)C(=O)N1C" \
    data/cilengitide/cilengitide_af3_input.json

python prepare_input.py \
    chai \
    "CC(C)[C@H]1C(=O)N[C@@H](CCCNC(N)=[NH2+])C(=O)NCC(=O)N[C@@H](CC(=O)[O-])C(=O)N[C@H](Cc2ccccc2)C(=O)N1C" \
    data/cilengitide/cilengitide_complex_chai_input.fasta \
    --protein_seq GPNICTTRGVSSCQQCLAVSPMCAWCSDEALPLGSPRCDLKENLLKDNCAPESIEFPVSEARVLEDRPLSDKGSGDSSQVTQVSPQRIALRLRPDDSKNFSIQVRQVEDYPVDIYYLMDLSYSMKDDLWSIQNLGTKLATQMRKLTSNLRIGFGAFVDKPVSPYMYISPPEALENPCYDMKTTCLPMFGYKHVLTLTDQVTRFNEEVKKQSVSRNRDAPEGGFDAIMQATVCDEKIGWRNDASHLLVFTTDAKTHIALDGRLAGIVQPNDGQCHVGSDNHYSASTTMDYPSLGLMTEKLSQKNINLIFAVTENVVNLYQNYSELIPGTTVGVLSMDSSNVLQLIVDAYGKIRSKVELEVRDLPEELSLSFNATCLNNEVIPGLKSCMGLKIGDTVSFSIEAKVRGCPQEKEKSFTIKPVGFKDSLIVQVTFDCDCACQAQAEPNSHRCNNGNGTFECGVCRCGPGWLGSQCECSEEDYRPSQQDECSPREGQPVCSQRGECLCGQCVCHSSDFGKITGKYCECDDFSCVRYKGEMCSGHGQCSCGDCLCDSDWTGYYCNCTTRTDTCMSSNGLLCSGRGKCECGSCVCIQPGSYGDTCEKCPTCPDACTFKKECVECKKFDREPYMTENTCNRYCRDEIESVKELKDTGKDAVNCTYKNEDDCVVRFQYYEDSSGKSILYVVEEPECPKGPD

python prepare_input.py \
    boltz \
    "CC(C)[C@H]1C(=O)N[C@@H](CCCNC(N)=[NH2+])C(=O)NCC(=O)N[C@@H](CC(=O)[O-])C(=O)N[C@H](Cc2ccccc2)C(=O)N1C" \
    data/cilengitide/cilengitide_complex_boltz_input.fasta \
    --protein_seq GPNICTTRGVSSCQQCLAVSPMCAWCSDEALPLGSPRCDLKENLLKDNCAPESIEFPVSEARVLEDRPLSDKGSGDSSQVTQVSPQRIALRLRPDDSKNFSIQVRQVEDYPVDIYYLMDLSYSMKDDLWSIQNLGTKLATQMRKLTSNLRIGFGAFVDKPVSPYMYISPPEALENPCYDMKTTCLPMFGYKHVLTLTDQVTRFNEEVKKQSVSRNRDAPEGGFDAIMQATVCDEKIGWRNDASHLLVFTTDAKTHIALDGRLAGIVQPNDGQCHVGSDNHYSASTTMDYPSLGLMTEKLSQKNINLIFAVTENVVNLYQNYSELIPGTTVGVLSMDSSNVLQLIVDAYGKIRSKVELEVRDLPEELSLSFNATCLNNEVIPGLKSCMGLKIGDTVSFSIEAKVRGCPQEKEKSFTIKPVGFKDSLIVQVTFDCDCACQAQAEPNSHRCNNGNGTFECGVCRCGPGWLGSQCECSEEDYRPSQQDECSPREGQPVCSQRGECLCGQCVCHSSDFGKITGKYCECDDFSCVRYKGEMCSGHGQCSCGDCLCDSDWTGYYCNCTTRTDTCMSSNGLLCSGRGKCECGSCVCIQPGSYGDTCEKCPTCPDACTFKKECVECKKFDREPYMTENTCNRYCRDEIESVKELKDTGKDAVNCTYKNEDDCVVRFQYYEDSSGKSILYVVEEPECPKGPD

python prepare_input.py \
    af3 \
    "CC(C)[C@H]1C(=O)N[C@@H](CCCNC(N)=[NH2+])C(=O)NCC(=O)N[C@@H](CC(=O)[O-])C(=O)N[C@H](Cc2ccccc2)C(=O)N1C" \
    data/cilengitide/cilengitide_complex_af3_input.json \
    --protein_seq GPNICTTRGVSSCQQCLAVSPMCAWCSDEALPLGSPRCDLKENLLKDNCAPESIEFPVSEARVLEDRPLSDKGSGDSSQVTQVSPQRIALRLRPDDSKNFSIQVRQVEDYPVDIYYLMDLSYSMKDDLWSIQNLGTKLATQMRKLTSNLRIGFGAFVDKPVSPYMYISPPEALENPCYDMKTTCLPMFGYKHVLTLTDQVTRFNEEVKKQSVSRNRDAPEGGFDAIMQATVCDEKIGWRNDASHLLVFTTDAKTHIALDGRLAGIVQPNDGQCHVGSDNHYSASTTMDYPSLGLMTEKLSQKNINLIFAVTENVVNLYQNYSELIPGTTVGVLSMDSSNVLQLIVDAYGKIRSKVELEVRDLPEELSLSFNATCLNNEVIPGLKSCMGLKIGDTVSFSIEAKVRGCPQEKEKSFTIKPVGFKDSLIVQVTFDCDCACQAQAEPNSHRCNNGNGTFECGVCRCGPGWLGSQCECSEEDYRPSQQDECSPREGQPVCSQRGECLCGQCVCHSSDFGKITGKYCECDDFSCVRYKGEMCSGHGQCSCGDCLCDSDWTGYYCNCTTRTDTCMSSNGLLCSGRGKCECGSCVCIQPGSYGDTCEKCPTCPDACTFKKECVECKKFDREPYMTENTCNRYCRDEIESVKELKDTGKDAVNCTYKNEDDCVVRFQYYEDSSGKSILYVVEEPECPKGPD

# 6BE7
python prepare_input.py \
    chai \
    "C[C@@H](O)[C@@H]1NC(=O)[C@@H]2CCCN2C(=O)[C@H](CC(=O)[O-])NC(=O)[C@H](CC(=O)[O-])NC(=O)[C@@H](CCC(N)=O)NC(=O)[C@H](CCC(N)=O)NC(=O)[C@@H](CCCNC(N)=[NH2+])NC(=O)[C@H]2CCCN2C1=O" \
    data/6be7/6be7_chai_input.fasta

python prepare_input.py \
    boltz \
    "C[C@@H](O)[C@@H]1NC(=O)[C@@H]2CCCN2C(=O)[C@H](CC(=O)[O-])NC(=O)[C@H](CC(=O)[O-])NC(=O)[C@@H](CCC(N)=O)NC(=O)[C@H](CCC(N)=O)NC(=O)[C@@H](CCCNC(N)=[NH2+])NC(=O)[C@H]2CCCN2C1=O" \
    data/6be7/6be7_boltz_input.fasta

python prepare_input.py \
    af3 \
    "C[C@@H](O)[C@@H]1NC(=O)[C@@H]2CCCN2C(=O)[C@H](CC(=O)[O-])NC(=O)[C@H](CC(=O)[O-])NC(=O)[C@@H](CCC(N)=O)NC(=O)[C@H](CCC(N)=O)NC(=O)[C@@H](CCCNC(N)=[NH2+])NC(=O)[C@H]2CCCN2C1=O" \
    data/6be7/6be7_af3_input.json

# 6WPV
python prepare_input.py \
    chai \
    "CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H](CCC(N)=O)NC(=O)[C@H](C(C)C)NC(=O)[C@H](C)NC(=O)[C@H](C(C)C)NC(=O)[C@H]([C@@H](C)O)NC(=O)CNC1=O" \
    data/6wpv/6wpv_chai_input.fasta

python prepare_input.py \
    boltz \
    "CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H](CCC(N)=O)NC(=O)[C@H](C(C)C)NC(=O)[C@H](C)NC(=O)[C@H](C(C)C)NC(=O)[C@H]([C@@H](C)O)NC(=O)CNC1=O" \
    data/6wpv/6wpv_boltz_input.fasta

python prepare_input.py \
    af3 \
    "CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H](CCC(N)=O)NC(=O)[C@H](C(C)C)NC(=O)[C@H](C)NC(=O)[C@H](C(C)C)NC(=O)[C@H]([C@@H](C)O)NC(=O)CNC1=O" \
    data/6wpv/6wpv_af3_input.json

# 6BEN
python prepare_input.py \
    chai \
    "NC(=[NH2+])NCCC[C@@H]1NC(=O)[C@@H](CCC(N)=O)NC(=O)[C@H]2CCCN2C(=O)[C@H](CCC(N)=O)NC(=O)[C@@H](CCCNC(N)=[NH2+])NC(=O)[C@H](CCC(N)=O)NC(=O)[C@@H]2CCCN2C(=O)[C@@H](CCC(=O)[O-])NC1=O" \
    data/6ben/6ben_chai_input.fasta

python prepare_input.py \
    boltz \
    "NC(=[NH2+])NCCC[C@@H]1NC(=O)[C@@H](CCC(N)=O)NC(=O)[C@H]2CCCN2C(=O)[C@H](CCC(N)=O)NC(=O)[C@@H](CCCNC(N)=[NH2+])NC(=O)[C@H](CCC(N)=O)NC(=O)[C@@H]2CCCN2C(=O)[C@@H](CCC(=O)[O-])NC1=O" \
    data/6ben/6ben_boltz_input.fasta

python prepare_input.py \
    af3 \
    "NC(=[NH2+])NCCC[C@@H]1NC(=O)[C@@H](CCC(N)=O)NC(=O)[C@H]2CCCN2C(=O)[C@H](CCC(N)=O)NC(=O)[C@@H](CCCNC(N)=[NH2+])NC(=O)[C@H](CCC(N)=O)NC(=O)[C@@H]2CCCN2C(=O)[C@@H](CCC(=O)[O-])NC1=O" \
    data/6ben/6ben_af3_input.json