import os
import argparse
from typing import Optional
import json


def prepare_chai_input(smiles: str, filepath: str, protein_seq: Optional[str] = None):
    if not filepath.endswith(".fasta"):
        raise ValueError("File path must end with .fasta extension for CHAI input.")
    if protein_seq:
        with open(filepath, "w") as f:
            f.write(f">protein|prot\n{protein_seq}\n>ligand|pep-edit-smi\n{smiles}")
    else:
        with open(filepath, "w") as f:
            f.write(f">ligand|pep-edit-smi\n{smiles}")


def prepare_boltz_input(smiles: str, filepath: str, protein_seq: Optional[str] = None):
    if not filepath.endswith(".fasta"):
        raise ValueError("File path must end with .fasta extension for BOLTZ input.")
    if protein_seq:
        with open(filepath, "w") as f:
            f.write(f">A|protein\n{protein_seq}\n>ligand|boltz-smi\n{smiles}")
    with open(filepath, "w") as f:
        f.write(f">A|smiles\n{smiles}")


def prepare_af3_input(smiles: str, filepath: str, protein_seq: Optional[str] = None):
    if not filepath.endswith(".json"):
        raise ValueError("File path must end with .json extension for AF3 input.")
    if protein_seq:
        d = {
            "name": "prot_pep",
            "modelSeeds": [1],
            "sequences": [
                {
                    "protein": {
                        "id": "A",
                        "sequence": f"{protein_seq}",
                        "unpairedMsa": f">query\n{protein_seq}\n",
                        "pairedMsa": f">query\n{protein_seq}\n",
                        "templates": [],
                    }
                },
                {"ligand": {"id": "B", "smiles": f"{smiles}"}},
            ],
            "dialect": "alphafold3",
            "version": 2,
        }
        out_json = json.dumps(d, indent=4)
        with open(filepath, "w") as f:
            f.write(out_json)
    else:
        d = {
            "name": "pep",
            "modelSeeds": [1],
            "sequences": [{"ligand": {"id": "A", "smiles": f"{smiles}"}}],
            "dialect": "alphafold3",
            "version": 2,
        }
        out_json = json.dumps(d, indent=4)
        with open(filepath, "w") as f:
            f.write(out_json)


def prepare_input(
    method: str, smiles: str, filepath: str, protein_seq: Optional[str] = None
):
    method = method.lower()
    if method == "chai":
        prepare_chai_input(smiles, filepath, protein_seq)
    elif method == "boltz":
        prepare_boltz_input(smiles, filepath, protein_seq)
    elif method == "af3":
        prepare_af3_input(smiles, filepath, protein_seq)
    else:
        raise ValueError(
            f"Unsupported method: {method}. Supported methods are 'chai', 'boltz', and 'af3'."
        )


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Prepare input files for different modeling methods starting from the SMILES generated by pep-edit."
    )
    parser.add_argument(
        "method", type=str, help="Modeling method: 'chai', 'boltz', or 'af3'."
    )
    parser.add_argument("smiles", type=str, help="SMILES string of the ligand.")
    parser.add_argument("filepath", type=str, help="Output file path.")
    parser.add_argument(
        "--protein_seq", type=str, default=None, help="Protein sequence (optional)."
    )
    args = parser.parse_args()
    prepare_input(
        method=args.method,
        smiles=args.smiles,
        filepath=args.filepath,
        protein_seq=args.protein_seq,
    )
